name: 'Setup OpenModelica'
description: 'Install OpenModelica using ubuntu packages from build.openmodelica.org'
inputs:
  version:
    description: 'OpenModelica version (exact)'
    required: true
    default: '1.16.2'
runs:
  using: "composite"
  steps:
    - run: |
        OM_BUILDS=https://build.openmodelica.org/omc/builds/linux/releases/${{ inputs.version }}
        echo "deb $OM_BUILDS `lsb_release -cs` release" | sudo tee /etc/apt/sources.list.d/openmodelica.list
        wget -qO - http://build.openmodelica.org/apt/openmodelica.asc | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install openmodelica
      shell: bash
