name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: |
      OM_BUILDS=https://build.openmodelica.org/omc/builds/linux/releases/${{ inputs.version }}
      echo "deb $OM_BUILDS `lsb_release -cs` release" > /etc/apt/sources.list.d/openmodelica.list
      echo "deb-src $OM_BUILDS `lsb_release -cs` release" >> /etc/apt/sources.list.d/openmodelica.list
      wget -q http://build.openmodelica.org/apt/openmodelica.asc -O- | sudo apt-key add -
      sudo apt-get update
      sudo apt-get install openmodelica
